/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mml.tehtava;


import java.io.IOException;
import java.util.ArrayList;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws IOException {
        
        Scanner scnr = new Scanner(System.in);

        ArrayList<Bill> bills = new ArrayList<Bill>();

        for (Customer c : CsvReader.getCustomers()) {
            bills.add(new Bill(c.getId()));
        }
 
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                JPanel gui = new JPanel(new BorderLayout());
                gui.setBorder(new EmptyBorder(2,3,2,3));

                JTextArea txtArea = new JTextArea(45, 45);

                for (Bill b : bills) {
                    if (b.getTotalCost() != 0)
                        txtArea.append(b.toString() + "\n\n###########\n\n");
                }
                

                gui.add(new JScrollPane(txtArea,
                        JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
                        JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS));
                
                JFrame frame = new JFrame("Laskut");
                frame.add(gui);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setLocationByPlatform(true);
                frame.pack();
                frame.setVisible(true);
            }
        };

        try {
            System.out.println("###############");
            for (Customer c : CsvReader.getCustomers()) {
                Bill b = new Bill(c.getId());
                if (b.getTotalCost() != 0) {
                    b.print();
                    System.out.println("###############");
                }
            }
            SwingUtilities.invokeLater(runnable);
            
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


        
    }



    
}
